
services:
  server:
    build:
      context: .
      dockerfile: server/dockerfile
    image: project-server:latest
    container_name: grpc_server
    networks:
      - nlpnet
    expose:
      - "50051"

  ui:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: project-ui:latest
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - server
    networks:
      - nlpnet

networks:
  nlpnet:
