# version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: server/dockerfile
    image: project-server:Shark
    container_name: Shark_server
    networks:
      - nlpnet
    expose:
      - "50051"
    restart: unless-stopped
    volumes:
      - ./server:/app  # Sync local 'server' folder to '/app' in container

  ui:
    build:
      context: .
      dockerfile: frontend/DockerFile
    image: project-ui:Shark
    container_name: client
    ports:
      - "8501:8501"
    depends_on:
      - server
    networks:
      - nlpnet
    environment:
      - GRPC_ADDRESS=grpc_server:50051
    restart: unless-stopped
    volumes:
      - ./frontend:/app  # Sync local 'frontend' folder to '/app' in container

networks:
  nlpnet:
    driver: bridge
