#version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: server/dockerfile
    image: project-server:latest
    container_name: grpc_server
    networks:
      - nlpnet
    expose:
      - "50051"
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: project-ui:latest
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - server
    networks:
      - nlpnet
    environment:
      - GRPC_ADDRESS=grpc_server:50051
    restart: unless-stopped

networks:
  nlpnet:
    driver: bridge
