# version: '3.9'

services:
  tts-server:
    build:
      context: .
      dockerfile: server/dockerfile
    image: project-server:latest
    container_name: tts-server
    networks:
      - ttsnet
    ports:
      - "50051:50051"  # Expose port outside container too
    restart: unless-stopped
    volumes:
      - ./generated_audio:/app/generated_audio  # Persistent storage for audio
      - ./model_cache:/root/.cache  # Cache downloaded models
    environment:
      - RUNNING_IN_DOCKER=true

  streamlit-ui:
    build:
      context: .
      dockerfile: frontend/DockerFile
    image: project-ui:latest
    container_name: tts-ui
    ports:
      - "8501:8501"
    depends_on:
      - tts-server
    networks:
      - ttsnet
    environment:
      - TTS_SERVER_HOST=tts-server
      - TTS_SERVER_PORT=50051
      - RUNNING_IN_DOCKER=true
    restart: unless-stopped
    volumes:
      - ./generated_audio:/app/generated_audio  # Share audio with server

networks:
  ttsnet:
    driver: bridge
